[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "StrideSim"
author = "Jinwon Kim"
maintainer = "Jinwon Kim"
description="Quadruped robot simulation from A to Z"
repository = "https://github.com/isaac-sim/IsaacLabExtensionTemplate.git"
keywords = ["extension", "quadruped robot", "isaaclab"]

[dependencies]
# "omni.isaac.lab" = {}
# "omni.isaac.lab_assets" = {}
# "omni.isaac.lab_tasks" = {}
# NOTE: Add additional dependencies here
# FIXME: 왜 에러가 나는 부분인지 확인하고 수정

[[python.module]]
name = "StrideSim"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
