name: 코드 품질 검사

on:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Python 설정
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: pre-commit 캐시 설정
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-
    - name: pre-commit 설치
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: pre-commit 실행
      run: pre-commit run --all-files
